name = "nusantaratrip-api"
main = "src/index.ts"
compatibility_date = "2024-03-29"

[[d1_databases]]
binding = "DB"
database_name = "nusantaratrip_db"
database_id = "caef027c-c775-4913-98bb-48656ee9289d"